# Generated by Django 3.2.9 on 2022-03-29 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('center_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('center_name', models.CharField(max_length=40, unique=True)),
                ('center_code', models.CharField(max_length=40, unique=True)),
                ('center_capacity', models.IntegerField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('exam_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('exam_name', models.CharField(max_length=65, unique=True)),
                ('exam_code', models.CharField(max_length=40, unique=True)),
                ('exam_is_cat', models.BooleanField()),
                ('exam_duration', models.CharField(max_length=10)),
                ('exam_no_questions', models.IntegerField()),
                ('exam_cut_of_mark', models.IntegerField()),
                ('exam_level', models.CharField(choices=[('National', 'National'), ('State', 'State'), ('Local', 'Local')], max_length=40)),
                ('exam_time', models.TimeField()),
                ('exam_date', models.DateField()),
                ('exam_year', models.IntegerField(blank=True, null=True)),
                ('exam_type', models.CharField(choices=[('Descriptive', 'Descriptive'), ('Lab', 'Lab'), ('Multiple_choice', 'Multiple_choice')], max_length=20, verbose_name='Type')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question_Exam_Bridge',
            fields=[
                ('qebridge_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('marks_to_add', models.IntegerField()),
                ('marks_to_deduct', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_exam_bridge', to='onlineexamapp.exam')),
            ],
        ),
        migrations.CreateModel(
            name='Question_Master',
            fields=[
                ('question_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=120, unique=True)),
                ('question_difficulty_level', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Difficult', 'Difficult')], max_length=20, verbose_name='Level')),
                ('question_type', models.CharField(choices=[('Descriptive', 'Descriptive'), ('Lab', 'Lab'), ('Multiple_choice', 'Multiple_choice')], max_length=20, verbose_name='Type')),
                ('max_no_option', models.IntegerField(blank=True, default=1, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question_Option',
            fields=[
                ('option_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('option', models.CharField(max_length=40, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_option', to='onlineexamapp.question_master')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('studen_name', models.CharField(max_length=40)),
                ('email_id', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=40, unique=True)),
                ('subject_code', models.CharField(max_length=40, unique=True)),
                ('subject_category', models.CharField(choices=[('Arts', 'Arts'), ('Science', 'Science'), ('Language', 'Language'), ('Management', 'Management'), ('Technology', 'Technology')], max_length=40, verbose_name='Category')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Exam_Flag',
            fields=[
                ('studentexam_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('E', 'E'), ('M', 'M'), ('D', 'D')], max_length=20, verbose_name='Level')),
                ('count_attempted_questions', models.IntegerField()),
                ('examid', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.PROTECT, related_name='student_exam_flag', to='onlineexamapp.exam')),
                ('studentid', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.PROTECT, related_name='student_exam_flag', to='onlineexamapp.student')),
            ],
        ),
        migrations.CreateModel(
            name='Questions_Answer_bridge',
            fields=[
                ('qabridge_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('answer', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.PROTECT, related_name='question_answer_bridge', to='onlineexamapp.question_option')),
                ('qebridge_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_answer_bridge', to='onlineexamapp.question_exam_bridge')),
            ],
        ),
        migrations.AddField(
            model_name='question_master',
            name='question_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_master', to='onlineexamapp.subject'),
        ),
        migrations.AddField(
            model_name='question_exam_bridge',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_exam_bridge', to='onlineexamapp.question_master'),
        ),
        migrations.CreateModel(
            name='Exam_Subject_Bridge',
            fields=[
                ('esbridge_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('no_questions', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_subject_bridge', to='onlineexamapp.exam')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_subject_bridge', to='onlineexamapp.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Exam_Paper',
            fields=[
                ('exam_paperid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('options', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.PROTECT, related_name='exam_paper', to='onlineexamapp.question_option')),
                ('question', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.PROTECT, related_name='exam_paper', to='onlineexamapp.question_exam_bridge')),
            ],
        ),
        migrations.CreateModel(
            name='Answer_Sheet',
            fields=[
                ('answer_sheetid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('exam_date', models.DateField()),
                ('sl_no', models.IntegerField()),
                ('correct_answer', models.BooleanField(default=True)),
                ('marks', models.IntegerField()),
                ('correct_answerid', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.PROTECT, related_name='answer_sheet', to='onlineexamapp.questions_answer_bridge')),
                ('examid', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.PROTECT, related_name='answer_sheet', to='onlineexamapp.exam')),
                ('questionid', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.PROTECT, related_name='answer_sheet', to='onlineexamapp.question_master')),
                ('student_answerid', models.ForeignKey(default=1, max_length=100, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='answer_sheet', to='onlineexamapp.question_option')),
                ('studentid', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.PROTECT, related_name='answer_sheet', to='onlineexamapp.student')),
            ],
        ),
    ]
